# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run build
    - run: npm run blog:build
    - run: git config --local user.email "action@github.com";
           git config --local user.name "GitHub Action";
           git config advice.addIgnoredFile false;
           git add dist;
           git commit -m "(dist/*) Regenerate static files.";
           exists=$(git show-ref refs/heads/master);
           if [ -n "$exists" ]
           then
           git branch -d master
           fi
           git subtree push --prefix dist origin master
      env:
        CI: true
